### ISSUE TITLE
Group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by sanieni6** [sanieni6/Space-Travelers-Hub#25]
# Group capstone: set up your Kanban board
In this activity, My team will prepare a Kanban board with a GitHub project:
https://github.com/sanieni6/Space-Travelers-Hub/projects/1
My team is made up of @sanieni6 , @johnie261  and @Cabraham1
For this project we choose working in the next sections:
[Luis](@sanieni6 ) - Rockets
[Johnie](@johnie261 ) - MIssions 
[Abraham](@Cabraham1 ) - Dragons

**Comment by zieeco** [comment]
# status: APPROVED :green_circle: :100: 

Hi, @Team, 


<img height="230" src="https://media0.giphy.com/media/7hyhCyGbFX50Vc9jah/giphy.gif"/>

Good job so far 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⚡ 

✅ Descriptive PR 👍 
✅ Nice design 🔥 
✅ Linters are passing 👏 
✅ Kanban setup correctly 👍 


## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
